from tkinter import *

window = Tk()
width = 400
height = 950
window.title('Guest Information')
window.geometry('400x950')
window.resizable(False, False)
label_frame = Frame(window, width=width, height=height, bg='white')
guest_name_label = Label(label_frame, text='Guest Name', bg='white', fg='light gray', font=('Arial', 16)).place(x=40, y=40)
guest_name_text = Label(label_frame, text='Henry Mo', bg='white', fg='black', font=('Arial', 16)).place(x=40, y=80)
check_in_label = Label(label_frame, text='Check In Date and Time', bg='white', fg='light gray', font=('Arial', 16)).place(x=40, y=140)
check_in_text = Label(label_frame, text='4/4/2021 7:38PM', bg='white', fg='black', font=('Arial', 16)).place(x=40, y=180)
expected_check_out_label = Label(label_frame, text='Expected Check Out Date and Time', bg='white', fg='light gray', font=('Arial', 16)).place(x=40, y=240)
expected_check_out_text = Label(label_frame, text='4/5/2021 7:38PM', bg='white', fg='black', font=('Arial', 16)).place(x=40, y=280)
room_type_label = Label(label_frame, text='Room Type', bg='white', fg='light gray', font=('Arial', 16)).place(x=40, y=340)
room_type_text = Label(label_frame, text='King', bg='white', fg='black', font=('Arial', 16)).place(x=40, y=380)
room_number_label = Label(label_frame, text='Room Number', bg='white', fg='light gray', font=('Arial', 16)).place(x=40, y=440)
room_number_text = Label(label_frame, text='1', bg='white', fg='black', font=('Arial', 16)).place(x=40, y=480)
room_rate_label = Label(label_frame, text='Room Rate ($/Day)', bg='white', fg='light gray', font=('Arial', 16)).place(x=40, y=540)
room_rate_text = Label(label_frame, text='50', bg='white', fg='black', font=('Arial', 16)).place(x=40, y=580)
total_charge_label = Label(label_frame, text='Total Charge', bg='white', fg='light gray', font=('Arial', 16)).place(x=40, y=640)
total_charge_text = Label(label_frame, text='50', bg='white', fg='black', font=('Arial', 16)).place(x=40, y=680)
payments_made_label = Label(label_frame, text='Payments Made', bg='white', fg='light gray', font=('Arial', 16)).place(x=40, y=740)
payments_made_text = Label(label_frame, text='50', bg='white', fg='black', font=('Arial', 16)).place(x=40, y=780)
balance_label = Label(label_frame, text='Balance', bg='white', fg='light gray', font=('Arial', 16)).place(x=40, y=840)
balance_text = Label(label_frame, text='0', bg='white', fg='black', font=('Arial', 16)).place(x=40, y=880)
label_frame.place(x=0, y=0)
window.mainloop()